name: globe_cast_live_meeting

description: A flutter app
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  auto_route: ^7.4.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  phosphor_flutter: ^2.0.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
  path: ^1.8.3
  gap: ^3.0.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.2
  scabld_safe_area_insets: ^1.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: any
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/files/
    - assets/icons/
    - assets/images/
